# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef28041048ee3482b6acd08ca20c04f2b395f8d3d82dfa812a9b362505774db24f124594d472577eba4937e24a31e3544983dd9744cc91794038dfe2dcc698d8

test:
  secret_key_base: 58cc07d6cbc444adc5fb89d25c84e00c8f321ef2986a5d5d4475f5cff7d9362e1bb204ad2090c7ea2974bdd07226f151c6f55e75e84e92fcae55b831e2b08f4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
